name: CI/CD Workflow

on:
  push:
    branches:
      - main # O deploy será feito apenas quando houver um push na branch "main"
  pull_request:
    branches:
      - main # Também executa testes ao criar pull requests para "main"

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Define a versão do Node.js

      - name: Install dependencies
        run: npm install

  lint_and_test:
    runs-on: ubuntu-latest

    needs: install_dependencies # Este job só começa após instalar dependências

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: npm run test -- --ci
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: lint_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        run: |
          npm i -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
